# Generated by Django 4.0.5 on 2022-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rekaps',
            fields=[
                ('id_rekaps', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_yt', models.CharField(max_length=100)),
                ('nama_video', models.CharField(max_length=100)),
                ('hasil_transkripsi', models.TextField()),
                ('hasil_deteksi', models.TextField()),
                ('klasifikasi', models.CharField(max_length=1)),
                ('tanggal', models.DateTimeField()),
            ],
        ),
    ]
