# Generated by Django 4.0.5 on 2022-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxic', '0002_rename_rekaps_rekapitulasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='kasar',
            fields=[
                ('id_kasar', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
