# Generated by Django 4.0.5 on 2022-08-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxic', '0003_kasar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kasar',
        ),
    ]
