# Generated by Django 4.0.5 on 2022-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxic', '0004_delete_kasar'),
    ]

    operations = [
        migrations.CreateModel(
            name='kasar',
            fields=[
                ('id_kasar', models.BigAutoField(primary_key=True, serialize=False)),
                ('kata_kasar', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
